//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleGodmist.locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locale_items {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale_items() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleGodmist.locale.locale_items", typeof(locale_items).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adamantite ore.
        /// </summary>
        internal static string AdamantiteOre {
            get {
                return ResourceManager.GetString("AdamantiteOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annodite ore.
        /// </summary>
        internal static string AnnoditeOre {
            get {
                return ResourceManager.GetString("AnnoditeOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium.
        /// </summary>
        internal static string Chromium {
            get {
                return ResourceManager.GetString("Chromium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cifilm ore.
        /// </summary>
        internal static string CifilmOre {
            get {
                return ResourceManager.GetString("CifilmOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal.
        /// </summary>
        internal static string Coal {
            get {
                return ResourceManager.GetString("Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt ore.
        /// </summary>
        internal static string CobaltOre {
            get {
                return ResourceManager.GetString("CobaltOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper ore.
        /// </summary>
        internal static string CopperOre {
            get {
                return ResourceManager.GetString("CopperOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert gem.
        /// </summary>
        internal static string DesertGem {
            get {
                return ResourceManager.GetString("DesertGem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold ore.
        /// </summary>
        internal static string GoldOre {
            get {
                return ResourceManager.GetString("GoldOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron ore.
        /// </summary>
        internal static string IronOre {
            get {
                return ResourceManager.GetString("IronOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteorite chunk.
        /// </summary>
        internal static string MeteoriteChunk {
            get {
                return ResourceManager.GetString("MeteoriteChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon dust.
        /// </summary>
        internal static string Moondust {
            get {
                return ResourceManager.GetString("Moondust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nefolite ore.
        /// </summary>
        internal static string NefoliteOre {
            get {
                return ResourceManager.GetString("NefoliteOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel ore.
        /// </summary>
        internal static string NickelOre {
            get {
                return ResourceManager.GetString("NickelOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orichalcum ore.
        /// </summary>
        internal static string OrichalcumOre {
            get {
                return ResourceManager.GetString("OrichalcumOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece of zinc.
        /// </summary>
        internal static string PieceOfZinc {
            get {
                return ResourceManager.GetString("PieceOfZinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutile.
        /// </summary>
        internal static string Rutile {
            get {
                return ResourceManager.GetString("Rutile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver ore.
        /// </summary>
        internal static string SilverOre {
            get {
                return ResourceManager.GetString("SilverOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphalerite.
        /// </summary>
        internal static string Sphalerite {
            get {
                return ResourceManager.GetString("Sphalerite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin ore.
        /// </summary>
        internal static string TinOre {
            get {
                return ResourceManager.GetString("TinOre", resourceCulture);
            }
        }
    }
}
