//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleGodmist.locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locale_main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale_main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleGodmist.locale.locale_main", typeof(locale_main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemist.
        /// </summary>
        internal static string Alchemist {
            get {
                return ResourceManager.GetString("Alchemist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacksmith.
        /// </summary>
        internal static string Blacksmith {
            get {
                return ResourceManager.GetString("Blacksmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catacombs.
        /// </summary>
        internal static string Catacombs {
            get {
                return ResourceManager.GetString("Catacombs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose difficulty.
        /// </summary>
        internal static string ChooseDifficulty {
            get {
                return ResourceManager.GetString("ChooseDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose item.
        /// </summary>
        internal static string ChooseItem {
            get {
                return ResourceManager.GetString("ChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose sorting method.
        /// </summary>
        internal static string ChooseSortingMethod {
            get {
                return ResourceManager.GetString("ChooseSortingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount entered is too high!.
        /// </summary>
        internal static string ChoseTooMany {
            get {
                return ResourceManager.GetString("ChoseTooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect plant.
        /// </summary>
        internal static string CollectPlant {
            get {
                return ResourceManager.GetString("CollectPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cove.
        /// </summary>
        internal static string Cove {
            get {
                return ResourceManager.GetString("Cove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current gold.
        /// </summary>
        internal static string CurrentGold {
            get {
                return ResourceManager.GetString("CurrentGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current level.
        /// </summary>
        internal static string CurrentLevel {
            get {
                return ResourceManager.GetString("CurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove item.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove.
        /// </summary>
        internal static string DeleteItemConfirmation {
            get {
                return ResourceManager.GetString("DeleteItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove equipment for other classes.
        /// </summary>
        internal static string DeleteJunk {
            get {
                return ResourceManager.GetString("DeleteJunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all equipment for other classes?.
        /// </summary>
        internal static string DeleteJunkConfirmation {
            get {
                return ResourceManager.GetString("DeleteJunkConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete save file.
        /// </summary>
        internal static string DeleteSaveFile {
            get {
                return ResourceManager.GetString("DeleteSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert.
        /// </summary>
        internal static string Desert {
            get {
                return ResourceManager.GetString("Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disarm trap.
        /// </summary>
        internal static string DisarmTrap {
            get {
                return ResourceManager.GetString("DisarmTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elvish Ruins.
        /// </summary>
        internal static string ElvishRuins {
            get {
                return ResourceManager.GetString("ElvishRuins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchanter.
        /// </summary>
        internal static string Enchanter {
            get {
                return ResourceManager.GetString("Enchanter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English__Language_ {
            get {
                return ResourceManager.GetString("English (Language)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit dungeon.
        /// </summary>
        internal static string ExitDungeon {
            get {
                return ResourceManager.GetString("ExitDungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit game.
        /// </summary>
        internal static string ExitGame {
            get {
                return ResourceManager.GetString("ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to menu.
        /// </summary>
        internal static string ExitToMenu {
            get {
                return ResourceManager.GetString("ExitToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to experience.
        /// </summary>
        internal static string ExperienceGenitive {
            get {
                return ResourceManager.GetString("ExperienceGenitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest.
        /// </summary>
        internal static string Forest {
            get {
                return ResourceManager.GetString("Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go down.
        /// </summary>
        internal static string GoDown {
            get {
                return ResourceManager.GetString("GoDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward.
        /// </summary>
        internal static string GoForward {
            get {
                return ResourceManager.GetString("GoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go up.
        /// </summary>
        internal static string GoUp {
            get {
                return ResourceManager.GetString("GoUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many to delete?.
        /// </summary>
        internal static string HowManyToDelete {
            get {
                return ResourceManager.GetString("HowManyToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a.
        /// </summary>
        internal static string Iam {
            get {
                return ResourceManager.GetString("Iam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect item.
        /// </summary>
        internal static string InspectItem {
            get {
                return ResourceManager.GetString("InspectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount cannot be negative!.
        /// </summary>
        internal static string IntBelowZero {
            get {
                return ResourceManager.GetString("IntBelowZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not in inventory.
        /// </summary>
        internal static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level up! You are now level.
        /// </summary>
        internal static string LevelUp {
            get {
                return ResourceManager.GetString("LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load game.
        /// </summary>
        internal static string LoadGame {
            get {
                return ResourceManager.GetString("LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were able to find a map of the current floor!.
        /// </summary>
        internal static string LocationScouted {
            get {
                return ResourceManager.GetString("LocationScouted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountains.
        /// </summary>
        internal static string Mountains {
            get {
                return ResourceManager.GetString("Mountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is.
        /// </summary>
        internal static string MyNameIs {
            get {
                return ResourceManager.GetString("MyNameIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameless.
        /// </summary>
        internal static string Nameless {
            get {
                return ResourceManager.GetString("Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightmare.
        /// </summary>
        internal static string Nightmare {
            get {
                return ResourceManager.GetString("Nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough of.
        /// </summary>
        internal static string NotEnoughItem {
            get {
                return ResourceManager.GetString("NotEnoughItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack is too heavy to pick up.
        /// </summary>
        internal static string NotEnoughWeight {
            get {
                return ResourceManager.GetString("NotEnoughWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on your way to the town of Arungard. Supposedly for twenty years no inhabitant of this city has experienced any daylight..
        /// </summary>
        internal static string Opening_1 {
            get {
                return ResourceManager.GetString("Opening_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve heard legends of the so-called Ghorn who uttered a spell and darkness enveloped the town..
        /// </summary>
        internal static string Opening_2 {
            get {
                return ResourceManager.GetString("Opening_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is all that you know though..
        /// </summary>
        internal static string Opening_3 {
            get {
                return ResourceManager.GetString("Opening_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reach the town. Its aged elfish walls and towers immediately had you impressed..
        /// </summary>
        internal static string Opening_4 {
            get {
                return ResourceManager.GetString("Opening_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You walk up to the guard near the gate..
        /// </summary>
        internal static string Opening_5 {
            get {
                return ResourceManager.GetString("Opening_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open inventory.
        /// </summary>
        internal static string OpenInventory {
            get {
                return ResourceManager.GetString("OpenInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot stash.
        /// </summary>
        internal static string OpenStash {
            get {
                return ResourceManager.GetString("OpenStash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paladin.
        /// </summary>
        internal static string PaladinLocative {
            get {
                return ResourceManager.GetString("PaladinLocative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        internal static string PaladinNominativeC {
            get {
                return ResourceManager.GetString("PaladinNominativeC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string Polish__Language_ {
            get {
                return ResourceManager.GetString("Polish (Language)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest log.
        /// </summary>
        internal static string QuestLog {
            get {
                return ResourceManager.GetString("QuestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest at campfire.
        /// </summary>
        internal static string RestAtCampfire {
            get {
                return ResourceManager.GetString("RestAtCampfire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save game.
        /// </summary>
        internal static string SaveGame {
            get {
                return ResourceManager.GetString("SaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scout.
        /// </summary>
        internal static string ScoutLocative {
            get {
                return ResourceManager.GetString("ScoutLocative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scout.
        /// </summary>
        internal static string ScoutNominativeC {
            get {
                return ResourceManager.GetString("ScoutNominativeC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select expedition destination:.
        /// </summary>
        internal static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show character.
        /// </summary>
        internal static string ShowCharacter {
            get {
                return ResourceManager.GetString("ShowCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorcerer.
        /// </summary>
        internal static string SorcererLocative {
            get {
                return ResourceManager.GetString("SorcererLocative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcerer.
        /// </summary>
        internal static string SorcererNominativeC {
            get {
                return ResourceManager.GetString("SorcererNominativeC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort inventory.
        /// </summary>
        internal static string SortInventory {
            get {
                return ResourceManager.GetString("SortInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start expedition.
        /// </summary>
        internal static string StartExpedition {
            get {
                return ResourceManager.GetString("StartExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swamp.
        /// </summary>
        internal static string Swamp {
            get {
                return ResourceManager.GetString("Swamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temple.
        /// </summary>
        internal static string Temple {
            get {
                return ResourceManager.GetString("Temple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to inspect.
        /// </summary>
        internal static string ToInspect {
            get {
                return ResourceManager.GetString("ToInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to remove.
        /// </summary>
        internal static string ToRemove {
            get {
                return ResourceManager.GetString("ToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to use.
        /// </summary>
        internal static string ToUse {
            get {
                return ResourceManager.GetString("ToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you, and what is your business in this town?.
        /// </summary>
        internal static string TownGuard_Line {
            get {
                return ResourceManager.GetString("TownGuard_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arungard Town Guard.
        /// </summary>
        internal static string TownGuard_Name {
            get {
                return ResourceManager.GetString("TownGuard_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use item.
        /// </summary>
        internal static string UseItem {
            get {
                return ResourceManager.GetString("UseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warrior.
        /// </summary>
        internal static string WarriorLocative {
            get {
                return ResourceManager.GetString("WarriorLocative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        internal static string WarriorNominativeC {
            get {
                return ResourceManager.GetString("WarriorNominativeC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You gain.
        /// </summary>
        internal static string YouGain {
            get {
                return ResourceManager.GetString("YouGain", resourceCulture);
            }
        }
    }
}
