//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleGodmist.locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locale_items {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale_items() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleGodmist.locale.locale_items", typeof(locale_items).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adamantite ore.
        /// </summary>
        internal static string AdamantiteOre {
            get {
                return ResourceManager.GetString("AdamantiteOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemy.
        /// </summary>
        internal static string Alchemy {
            get {
                return ResourceManager.GetString("Alchemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancient.
        /// </summary>
        internal static string Ancient {
            get {
                return ResourceManager.GetString("Ancient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annodite ore.
        /// </summary>
        internal static string AnnoditeOre {
            get {
                return ResourceManager.GetString("AnnoditeOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Galdurite.
        /// </summary>
        internal static string ArmorGaldurite {
            get {
                return ResourceManager.GetString("ArmorGaldurite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium.
        /// </summary>
        internal static string Chromium {
            get {
                return ResourceManager.GetString("Chromium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cifilm ore.
        /// </summary>
        internal static string CifilmOre {
            get {
                return ResourceManager.GetString("CifilmOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal.
        /// </summary>
        internal static string Coal {
            get {
                return ResourceManager.GetString("Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobalt ore.
        /// </summary>
        internal static string CobaltOre {
            get {
                return ResourceManager.GetString("CobaltOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper ore.
        /// </summary>
        internal static string CopperOre {
            get {
                return ResourceManager.GetString("CopperOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged.
        /// </summary>
        internal static string Damaged {
            get {
                return ResourceManager.GetString("Damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert gem.
        /// </summary>
        internal static string DesertGem {
            get {
                return ResourceManager.GetString("DesertGem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyed.
        /// </summary>
        internal static string Destroyed {
            get {
                return ResourceManager.GetString("Destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godly.
        /// </summary>
        internal static string Godly {
            get {
                return ResourceManager.GetString("Godly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold ore.
        /// </summary>
        internal static string GoldOre {
            get {
                return ResourceManager.GetString("GoldOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron ore.
        /// </summary>
        internal static string IronOre {
            get {
                return ResourceManager.GetString("IronOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk.
        /// </summary>
        internal static string Junk {
            get {
                return ResourceManager.GetString("Junk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        internal static string Legendary {
            get {
                return ResourceManager.GetString("Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Bag.
        /// </summary>
        internal static string LootBag {
            get {
                return ResourceManager.GetString("LootBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteorite chunk.
        /// </summary>
        internal static string MeteoriteChunk {
            get {
                return ResourceManager.GetString("MeteoriteChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon dust.
        /// </summary>
        internal static string Moondust {
            get {
                return ResourceManager.GetString("Moondust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mythical.
        /// </summary>
        internal static string Mythical {
            get {
                return ResourceManager.GetString("Mythical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nefolite ore.
        /// </summary>
        internal static string NefoliteOre {
            get {
                return ResourceManager.GetString("NefoliteOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickel ore.
        /// </summary>
        internal static string NickelOre {
            get {
                return ResourceManager.GetString("NickelOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orichalcum ore.
        /// </summary>
        internal static string OrichalcumOre {
            get {
                return ResourceManager.GetString("OrichalcumOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece of zinc.
        /// </summary>
        internal static string PieceOfZinc {
            get {
                return ResourceManager.GetString("PieceOfZinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potion.
        /// </summary>
        internal static string Potion {
            get {
                return ResourceManager.GetString("Potion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        internal static string Rarity {
            get {
                return ResourceManager.GetString("Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runeforging.
        /// </summary>
        internal static string Runeforging {
            get {
                return ResourceManager.GetString("Runeforging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutile.
        /// </summary>
        internal static string Rutile {
            get {
                return ResourceManager.GetString("Rutile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver ore.
        /// </summary>
        internal static string SilverOre {
            get {
                return ResourceManager.GetString("SilverOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smithing.
        /// </summary>
        internal static string Smithing {
            get {
                return ResourceManager.GetString("Smithing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphalerite.
        /// </summary>
        internal static string Sphalerite {
            get {
                return ResourceManager.GetString("Sphalerite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin ore.
        /// </summary>
        internal static string TinOre {
            get {
                return ResourceManager.GetString("TinOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        internal static string Uncommon {
            get {
                return ResourceManager.GetString("Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Galdurite.
        /// </summary>
        internal static string WeaponGaldurite {
            get {
                return ResourceManager.GetString("WeaponGaldurite", resourceCulture);
            }
        }
    }
}
